
service: optica
frameworkVersion: "3"

package:
  patterns:
    - "!./**"
    - "Handlers/**"
    - "Classes/**"
    - "Utils/**"
    - "DataBase/**"

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: python3.9

functions:
  UserApi:
    handler: Handlers/UserHandler.user
    events:
      - http:
          path: /get_user
          method: get
      - http:
          path: /create_user
          method: post
      - http:
          path: /update_user
          method: put
      - http:
          path: /delete_user
          method: delete

  DocumentTypeApi:
    handler: Handlers/DocumentTypeHandler.document_type
    events:
      - http:
          path: /get_document_types
          method: get
      - http:
          path: /create_document_type
          method: post
      - http:
          path: /update_document_type
          method: put
      - http:
          path: /delete_document_type
          method: delete

  MedicalHistoryApi:
    handler: Handlers/MedicalHistoryHandler.medical_history
    events:
      - http:
          path: /get_history
          method: get
      - http:
          path: /create_history
          method: post

  DoctorApi:
    handler: Handlers/DoctorHandler.doctor
    events:
      - http:
          path: /get_doctors
          method: get
      - http:
          path: /create_doctor
          method: post
      - http:
          path: /update_doctor
          method: put
      - http:
          path: /delete_doctor
          method: delete

  PatientApi:
    handler: Handlers/PatientHandler.patient
    events:
      - http:
          path: /get_patients
          method: get
      - http:
          path: /create_patient
          method: post
      - http:
          path: /update_patient
          method: put
      - http:
          path: /delete_patient
          method: delete

  # ConsultationApi:
  #   handler: Handlers/ConsultationHandler.consultation
  #   events:
  #     - http:
  #         path: /get_consultations
  #         method: get
  #     - http:
  #         path: /create_consultation
  #         method: post

  AuthApi:
    handler: Handlers/AuthHandler.auth
    events:
      - http:
          path: /auth
          method: post
